### ISSUE TITLE
Show the difficulty mods are on

### ISSUE THREAD

**Issue by STCapricorn** [Naxesss/Aiess#2]
currently, there's no way to tell which diff has gotten mods from just the embed, making it a bit troublesome to check who needs to reply to certain mods on a gd, for example.

**Comment by Naxesss** [comment]
setup a tab column in discussions table that should make implementing this a bit easier

![](https://i.imgur.com/l49tARl.png)

am thinking something like the below image could work, might make the footer a bit long but not sure where else to put it
have tried other places but it gets a bit cluttery being where the title/mapper are, and putting in embed title emphasizes it too much

![](https://i.imgur.com/Z2QuotX.png)

gonna do a few other things for now but ye including it somewhere is probably a good idea

**Comment by STCapricorn** [comment]
ye, this is good enough

**Comment by Naxesss** [comment]
ended up skipping the tab and just showing the diff since you can infer tab from whether the post begins with a timestamp

![](https://i.imgur.com/pvpiRBJ.png)

if the tab is General (All difficulties), it'll display like before without a diff after

can now also filter by tab/diff using e.g. `discussion-tab:timeline` and `discussion-difficulty:"gder's insane"`
so if you want a feed of stuff only on your gds you could do `+sub discussion-difficulty:"cap's %"`, for example
